name: Upload coverage

on: workflow_dispatch

jobs: 
  upload_coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.19.0

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: "pnpm"
      
      - name: Install dependencies
        run: pnpm i

      - name: Test and cover
        run: pnpm coverage

      - name: Publish coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
